# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWebEngineWidgets import QWebEngineView
from PyQt5.QtWidgets import QPushButton


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1070, 838)
        self.MainWindow = MainWindow
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainVerticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainVerticalLayout.setObjectName("mainVerticalLayout")
        self.mainHorizontalLayout = QtWidgets.QHBoxLayout()
        self.mainHorizontalLayout.setObjectName("mainHorizontalLayout")
        self.groupBoxMainText = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxMainText.setObjectName("groupBoxMainText")
        self.mainTextVerticalLayout = QtWidgets.QVBoxLayout(self.groupBoxMainText)
        self.mainTextVerticalLayout.setObjectName("mainTextVerticalLayout")
        self.mainTextWidget = QtWidgets.QWidget(self.groupBoxMainText)
        self.mainTextWidget.setObjectName("mainTextWidget")
        self.mainTextHorizontalLayout = QtWidgets.QHBoxLayout(self.mainTextWidget)
        self.mainTextHorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.mainTextHorizontalLayout.setObjectName("mainTextHorizontalLayout")
        self.lineEditMainText = QtWidgets.QLineEdit(self.mainTextWidget)
        self.lineEditMainText.setObjectName("lineEditMainText")
        self.mainTextHorizontalLayout.addWidget(self.lineEditMainText)
        self.openMainTextButton = QtWidgets.QPushButton(self.mainTextWidget)
        self.openMainTextButton.setObjectName("openMainTextButton")
        self.mainTextHorizontalLayout.addWidget(self.openMainTextButton)
        self.reloadMainTextButton = QtWidgets.QPushButton(self.mainTextWidget)
        self.reloadMainTextButton.setObjectName("reloadMainTextButton")
        self.mainTextHorizontalLayout.addWidget(self.reloadMainTextButton)
        self.spinBoxMainTextLimit = QtWidgets.QSpinBox(self.mainTextWidget)
        self.spinBoxMainTextLimit.setMaximum(100000)
        self.spinBoxMainTextLimit.setProperty("value", 10000)
        self.spinBoxMainTextLimit.setObjectName("spinBoxMainTextLimit")
        self.mainTextHorizontalLayout.addWidget(self.spinBoxMainTextLimit)



        self.toggle_button1 = QPushButton("Switch", self.MainWindow)

        self.mainTextHorizontalLayout.addWidget(self.toggle_button1)

        self.mainTextVerticalLayout.addWidget(self.mainTextWidget)
        self.textEditMainText = QtWidgets.QTextEdit(self.groupBoxMainText)
        self.textEditMainText.setMinimumSize(QtCore.QSize(0, 300))
        self.textEditMainText.setObjectName("textEditMainText")
        self.mainTextVerticalLayout.addWidget(self.textEditMainText)

        # QWebEngineView for HTML content
        self.web_viewMainText = QWebEngineView(self.MainWindow)
        self.web_viewMainText.hide()  # Start hidden
        self.mainTextVerticalLayout.addWidget(self.web_viewMainText)

        self.mainHorizontalLayout.addWidget(self.groupBoxMainText)
        self.groupBoxAlternativeText = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxAlternativeText.setObjectName("groupBoxAlternativeText")
        self.alternativeTextVerticalLayout = QtWidgets.QVBoxLayout(self.groupBoxAlternativeText)
        self.alternativeTextVerticalLayout.setObjectName("alternativeTextVerticalLayout")
        self.alternativeTextWidget = QtWidgets.QWidget(self.groupBoxAlternativeText)
        self.alternativeTextWidget.setObjectName("alternativeTextWidget")
        self.alternativeTextHorizontalLayout = QtWidgets.QHBoxLayout(self.alternativeTextWidget)
        self.alternativeTextHorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.alternativeTextHorizontalLayout.setObjectName("alternativeTextHorizontalLayout")
        self.lineEditAlternativeText = QtWidgets.QLineEdit(self.alternativeTextWidget)
        self.lineEditAlternativeText.setObjectName("lineEditAlternativeText")
        self.alternativeTextHorizontalLayout.addWidget(self.lineEditAlternativeText)
        self.openAlternativeTextButton = QtWidgets.QPushButton(self.alternativeTextWidget)
        self.openAlternativeTextButton.setObjectName("openAlternativeTextButton")
        self.alternativeTextHorizontalLayout.addWidget(self.openAlternativeTextButton)
        self.reloadAlternativeTextButton = QtWidgets.QPushButton(self.alternativeTextWidget)
        self.reloadAlternativeTextButton.setObjectName("reloadAlternativeTextButton")
        self.alternativeTextHorizontalLayout.addWidget(self.reloadAlternativeTextButton)
        self.spinBoxAlternativeTextLimit = QtWidgets.QSpinBox(self.alternativeTextWidget)
        self.spinBoxAlternativeTextLimit.setMaximum(100000)
        self.spinBoxAlternativeTextLimit.setProperty("value", 10000)
        self.spinBoxAlternativeTextLimit.setObjectName("spinBoxAlternativeTextLimit")
        self.alternativeTextHorizontalLayout.addWidget(self.spinBoxAlternativeTextLimit)

        self.toggle_button2 = QPushButton("Switch", self.MainWindow)

        self.alternativeTextHorizontalLayout.addWidget(self.toggle_button2)

        self.alternativeTextVerticalLayout.addWidget(self.alternativeTextWidget)

        self.textEditAlternativeText = QtWidgets.QTextEdit(self.groupBoxAlternativeText)
        self.textEditAlternativeText.setObjectName("textEditAlternativeText")
        self.alternativeTextVerticalLayout.addWidget(self.textEditAlternativeText)

        # QWebEngineView for HTML content
        self.web_viewAlternativeText = QWebEngineView(self.MainWindow)
        self.web_viewAlternativeText.hide()  # Start hidden
        self.alternativeTextVerticalLayout.addWidget(self.web_viewAlternativeText)


        self.mainHorizontalLayout.addWidget(self.groupBoxAlternativeText)
        self.mainVerticalLayout.addLayout(self.mainHorizontalLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabPreprocessing = QtWidgets.QWidget()
        self.tabPreprocessing.setObjectName("tabPreprocessing")
        self.preprocessingVerticalLayout = QtWidgets.QVBoxLayout(self.tabPreprocessing)
        self.preprocessingVerticalLayout.setObjectName("preprocessingVerticalLayout")
        self.preprocessingHorizontalLayout = QtWidgets.QHBoxLayout()
        self.preprocessingHorizontalLayout.setObjectName("preprocessingHorizontalLayout")
        self.clearPreprocessingButton = QtWidgets.QPushButton(self.tabPreprocessing)
        self.clearPreprocessingButton.setObjectName("clearPreprocessingButton")
        self.preprocessingHorizontalLayout.addWidget(self.clearPreprocessingButton)
        self.applyPreprocessingButton = QtWidgets.QPushButton(self.tabPreprocessing)
        self.applyPreprocessingButton.setObjectName("applyPreprocessingButton")
        self.preprocessingHorizontalLayout.addWidget(self.applyPreprocessingButton)
        self.preprocessingComboBox = QtWidgets.QComboBox(self.tabPreprocessing)
        self.preprocessingComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.preprocessingComboBox.setObjectName("preprocessingComboBox")
        self.preprocessingComboBox.addItem("")
        self.preprocessingHorizontalLayout.addWidget(self.preprocessingComboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.preprocessingHorizontalLayout.addItem(spacerItem)
        self.preprocessingVerticalLayout.addLayout(self.preprocessingHorizontalLayout)

        self.codePlaceholder = QtWidgets.QVBoxLayout()
        self.preprocessingVerticalLayout.addLayout(self.codePlaceholder)
        self.tabWidget.addTab(self.tabPreprocessing, "")
        self.tabTranslations = QtWidgets.QWidget()
        self.tabTranslations.setObjectName("tabTranslations")
        self.translationsVerticalLayout = QtWidgets.QVBoxLayout(self.tabTranslations)
        self.translationsVerticalLayout.setObjectName("translationsVerticalLayout")
        self.translationsHorizontalLayout = QtWidgets.QHBoxLayout()
        self.translationsHorizontalLayout.setObjectName("translationsHorizontalLayout")
        self.clearTranslationsButton = QtWidgets.QPushButton(self.tabTranslations)
        self.clearTranslationsButton.setObjectName("clearTranslationsButton")
        self.translationsHorizontalLayout.addWidget(self.clearTranslationsButton)
        self.applyTranslationsButton = QtWidgets.QPushButton(self.tabTranslations)
        self.applyTranslationsButton.setObjectName("applyTranslationsButton")
        self.translationsHorizontalLayout.addWidget(self.applyTranslationsButton)
        self.addTranslationButton = QtWidgets.QPushButton(self.tabTranslations)
        self.addTranslationButton.setObjectName("addTranslationButton")
        self.translationsHorizontalLayout.addWidget(self.addTranslationButton)
        self.editTranslationButton = QtWidgets.QPushButton(self.tabTranslations)
        self.editTranslationButton.setObjectName("editTranslationButton")
        self.translationsHorizontalLayout.addWidget(self.editTranslationButton)
        self.deleteTranslationButton = QtWidgets.QPushButton(self.tabTranslations)
        self.deleteTranslationButton.setObjectName("deleteTranslationButton")
        self.translationsHorizontalLayout.addWidget(self.deleteTranslationButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.translationsHorizontalLayout.addItem(spacerItem1)
        self.translationsVerticalLayout.addLayout(self.translationsHorizontalLayout)
        self.translationsTableHorizontalLayout = QtWidgets.QHBoxLayout()
        self.translationsTableHorizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.translationsTableHorizontalLayout.setObjectName("translationsTableHorizontalLayout")
        self.translationsTableWidget = QtWidgets.QTableWidget(self.tabTranslations)
        self.translationsTableWidget.setObjectName("translationsTableWidget")
        self.translationsTableWidget.setColumnCount(2)
        self.translationsTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.translationsTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.translationsTableWidget.setHorizontalHeaderItem(1, item)
        self.translationsTableWidget.horizontalHeader().setMinimumSectionSize(200)
        self.translationsTableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.translationsTableWidget.horizontalHeader().setStretchLastSection(True)
        self.translationsTableHorizontalLayout.addWidget(self.translationsTableWidget)
        self.translationsVerticalLayout.addLayout(self.translationsTableHorizontalLayout)
        self.tabWidget.addTab(self.tabTranslations, "")

        self.tabMappings = QtWidgets.QWidget()
        self.tabMappings.setObjectName("tabMappings")
        self.mappingsVerticalLayout = QtWidgets.QVBoxLayout(self.tabMappings)
        self.mappingsVerticalLayout.setObjectName("mappingsVerticalLayout")
        self.mappingsHorizontalLayout = QtWidgets.QHBoxLayout()
        self.mappingsHorizontalLayout.setObjectName("mappingsHorizontalLayout")
        self.clearMappingsButton = QtWidgets.QPushButton(self.tabMappings)
        self.clearMappingsButton.setObjectName("clearMappingsButton")
        self.mappingsHorizontalLayout.addWidget(self.clearMappingsButton)
        self.applyMappingsButton = QtWidgets.QPushButton(self.tabMappings)
        self.applyMappingsButton.setObjectName("applyMappingsButton")
        self.mappingsHorizontalLayout.addWidget(self.applyMappingsButton)
        self.addMappingButton = QtWidgets.QPushButton(self.tabMappings)
        self.addMappingButton.setObjectName("addMappingsButton")
        self.mappingsHorizontalLayout.addWidget(self.addMappingButton)
        self.editMappingButton = QtWidgets.QPushButton(self.tabMappings)
        self.editMappingButton.setObjectName("editMappingsButton")
        self.mappingsHorizontalLayout.addWidget(self.editMappingButton)
        self.deleteMappingButton = QtWidgets.QPushButton(self.tabMappings)
        self.deleteMappingButton.setObjectName("deleteMappingsButton")
        self.mappingsHorizontalLayout.addWidget(self.deleteMappingButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.mappingsHorizontalLayout.addItem(spacerItem1)
        self.mappingsVerticalLayout.addLayout(self.mappingsHorizontalLayout)
        self.mappingsTableHorizontalLayout = QtWidgets.QHBoxLayout()
        self.mappingsTableHorizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.mappingsTableHorizontalLayout.setObjectName("mappingsTableHorizontalLayout")
        self.mappingsTableWidget = QtWidgets.QTableWidget(self.tabMappings)
        self.mappingsTableWidget.setObjectName("mappingsTableWidget")
        self.mappingsTableWidget.setColumnCount(2)
        self.mappingsTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.mappingsTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.mappingsTableWidget.setHorizontalHeaderItem(1, item)
        self.mappingsTableWidget.horizontalHeader().setMinimumSectionSize(200)
        self.mappingsTableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.mappingsTableWidget.horizontalHeader().setStretchLastSection(True)
        self.mappingsTableHorizontalLayout.addWidget(self.mappingsTableWidget)
        self.mappingsVerticalLayout.addLayout(self.mappingsTableHorizontalLayout)
        self.tabWidget.addTab(self.tabMappings, "")


        self.tabClustering = QtWidgets.QWidget()
        self.tabClustering.setObjectName("tabClustering")
        self.clusteringVerticalLayout = QtWidgets.QVBoxLayout(self.tabClustering)
        self.clusteringVerticalLayout.setObjectName("clusteringVerticalLayout")
        self.clusteringHorizontalLayout = QtWidgets.QHBoxLayout()
        self.clusteringHorizontalLayout.setObjectName("clusteringHorizontalLayout")
        self.clearClusteringButton = QtWidgets.QPushButton(self.tabClustering)
        self.clearClusteringButton.setObjectName("clearClusteringButton")
        self.clusteringHorizontalLayout.addWidget(self.clearClusteringButton)
        self.applyClusteringButton = QtWidgets.QPushButton(self.tabClustering)
        self.applyClusteringButton.setObjectName("applyClusteringButton")
        self.clusteringHorizontalLayout.addWidget(self.applyClusteringButton)
        self.addClusterButton = QtWidgets.QPushButton(self.tabClustering)
        self.addClusterButton.setObjectName("addClusterButton")
        self.clusteringHorizontalLayout.addWidget(self.addClusterButton)
        self.editClusterButton = QtWidgets.QPushButton(self.tabClustering)
        self.editClusterButton.setObjectName("editClusterButton")
        self.clusteringHorizontalLayout.addWidget(self.editClusterButton)
        self.deleteClusterButton = QtWidgets.QPushButton(self.tabClustering)
        self.deleteClusterButton.setObjectName("deleteClusterButton")
        self.clusteringHorizontalLayout.addWidget(self.deleteClusterButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.clusteringHorizontalLayout.addItem(spacerItem2)
        self.clusteringVerticalLayout.addLayout(self.clusteringHorizontalLayout)
        self.clusteringDetailsHorizontalLayout = QtWidgets.QHBoxLayout()
        self.clusteringDetailsHorizontalLayout.setObjectName("clusteringDetailsHorizontalLayout")
        self.clusteringTreeWidget = QtWidgets.QTreeWidget(self.tabClustering)
        self.clusteringTreeWidget.setMaximumSize(QtCore.QSize(400, 16777215))
        self.clusteringTreeWidget.setObjectName("clusteringTreeWidget")
        self.clusteringDetailsHorizontalLayout.addWidget(self.clusteringTreeWidget)
        self.clusteringFormLayout = QtWidgets.QFormLayout()
        self.clusteringFormLayout.setContentsMargins(-1, -1, 0, -1)
        self.clusteringFormLayout.setObjectName("clusteringFormLayout")
        self.labelClusterName = QtWidgets.QLabel(self.tabClustering)
        self.labelClusterName.setObjectName("labelClusterName")
        self.clusteringFormLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelClusterName)
        self.labelClusterParts = QtWidgets.QLabel(self.tabClustering)
        self.labelClusterParts.setObjectName("labelClusterParts")
        self.clusteringFormLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelClusterParts)
        self.labelClusterPatterns = QtWidgets.QLabel(self.tabClustering)
        self.labelClusterPatterns.setObjectName("labelClusterPatterns")
        self.clusteringFormLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelClusterPatterns)
        self.labelClusterCode = QtWidgets.QLabel(self.tabClustering)
        self.labelClusterCode.setObjectName("labelClusterCode")
        self.clusteringFormLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelClusterCode)
        self.lineEditClusterName = QtWidgets.QLineEdit(self.tabClustering)
        self.lineEditClusterName.setObjectName("lineEditClusterName")
        self.clusteringFormLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditClusterName)
        self.clusterPartsVerticalLayout = QtWidgets.QVBoxLayout()
        self.clusterPartsVerticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.clusterPartsVerticalLayout.setObjectName("clusterPartsVerticalLayout")
        self.clusterPartsHorizontalLayout = QtWidgets.QHBoxLayout()
        self.clusterPartsHorizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.clusterPartsHorizontalLayout.setObjectName("clusterPartsHorizontalLayout")
        self.addPartButton = QtWidgets.QPushButton(self.tabClustering)
        self.addPartButton.setObjectName("addPartButton")
        self.clusterPartsHorizontalLayout.addWidget(self.addPartButton)
        self.editPartButton = QtWidgets.QPushButton(self.tabClustering)
        self.editPartButton.setObjectName("editPartButton")
        self.clusterPartsHorizontalLayout.addWidget(self.editPartButton)
        self.deletePartButton = QtWidgets.QPushButton(self.tabClustering)
        self.deletePartButton.setObjectName("deletePartButton")
        self.clusterPartsHorizontalLayout.addWidget(self.deletePartButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.clusterPartsHorizontalLayout.addItem(spacerItem3)
        self.clusterPartsVerticalLayout.addLayout(self.clusterPartsHorizontalLayout)
        self.clusterPartsListWidget = QtWidgets.QListWidget(self.tabClustering)
        self.clusterPartsListWidget.setObjectName("clusterPartsListWidget")
        self.clusterPartsVerticalLayout.addWidget(self.clusterPartsListWidget)
        self.clusteringFormLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.clusterPartsVerticalLayout)
        self.clusterPatternsVerticalLayout = QtWidgets.QVBoxLayout()
        self.clusterPatternsVerticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.clusterPatternsVerticalLayout.setObjectName("clusterPatternsVerticalLayout")
        self.clusterPatternsHorizontalLayout = QtWidgets.QHBoxLayout()
        self.clusterPatternsHorizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.clusterPatternsHorizontalLayout.setObjectName("clusterPatternsHorizontalLayout")
        self.addPatternButton = QtWidgets.QPushButton(self.tabClustering)
        self.addPatternButton.setObjectName("addPatternButton")
        self.clusterPatternsHorizontalLayout.addWidget(self.addPatternButton)
        self.editPatternButton = QtWidgets.QPushButton(self.tabClustering)
        self.editPatternButton.setObjectName("editPatternButton")
        self.clusterPatternsHorizontalLayout.addWidget(self.editPatternButton)
        self.deletePatternButton = QtWidgets.QPushButton(self.tabClustering)
        self.deletePatternButton.setObjectName("deletePatternButton")
        self.clusterPatternsHorizontalLayout.addWidget(self.deletePatternButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.clusterPatternsHorizontalLayout.addItem(spacerItem4)
        self.clusterPatternsVerticalLayout.addLayout(self.clusterPatternsHorizontalLayout)
        self.clusterPatternsListWidget = QtWidgets.QListWidget(self.tabClustering)
        self.clusterPatternsListWidget.setObjectName("clusterPatternsListWidget")
        self.clusterPatternsVerticalLayout.addWidget(self.clusterPatternsListWidget)
        self.clusteringFormLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.clusterPatternsVerticalLayout)


        self.clusterCodeWidget = QtWidgets.QVBoxLayout(self.tabClustering)
        self.clusterCodeWidget.setObjectName("clusterCodeWidget")

        self.clusteringFormLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.clusterCodeWidget)
        self.labelClusterConfigs = QtWidgets.QLabel(self.tabClustering)
        self.labelClusterConfigs.setObjectName("labelClusterConfigs")
        self.clusteringFormLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelClusterConfigs)
        self.clusterConfigsFormLayout = QtWidgets.QFormLayout()
        self.clusterConfigsFormLayout.setObjectName("clusterConfigsFormLayout")
        self.labelMinLength = QtWidgets.QLabel(self.tabClustering)
        self.labelMinLength.setObjectName("labelMinLength")
        self.clusterConfigsFormLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelMinLength)
        self.lineEditMinLength = QtWidgets.QLineEdit(self.tabClustering)
        self.lineEditMinLength.setObjectName("lineEditMinLength")
        self.clusterConfigsFormLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditMinLength)
        self.labelMaxLength = QtWidgets.QLabel(self.tabClustering)
        self.labelMaxLength.setObjectName("labelMaxLength")
        self.clusterConfigsFormLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelMaxLength)
        self.lineEditMaxLength = QtWidgets.QLineEdit(self.tabClustering)
        self.lineEditMaxLength.setObjectName("lineEditMaxLength")
        self.clusterConfigsFormLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditMaxLength)
        self.labelPartsWeight = QtWidgets.QLabel(self.tabClustering)
        self.labelPartsWeight.setObjectName("labelPartsWeight")
        self.clusterConfigsFormLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelPartsWeight)
        self.labelRegexWeight = QtWidgets.QLabel(self.tabClustering)
        self.labelRegexWeight.setObjectName("labelRegexWeight")
        self.clusterConfigsFormLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelRegexWeight)
        self.lineEditPartsWeight = QtWidgets.QLineEdit(self.tabClustering)
        self.lineEditPartsWeight.setObjectName("lineEditPartsWeight")
        self.clusterConfigsFormLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditPartsWeight)
        self.lineEditRegexWeight = QtWidgets.QLineEdit(self.tabClustering)
        self.lineEditRegexWeight.setObjectName("lineEditRegexWeight")
        self.clusterConfigsFormLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEditRegexWeight)

        self.parserComboBox = QtWidgets.QComboBox(self.tabClustering)
        self.parserComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.parserComboBox.setObjectName("parserComboBox")
        self.parserComboBox.addItem("EMPTY", userData="""def parse(line):
    try:
        line = line.split("#")[1]
    except:
        return {}
""")
        self.parserComboBox.addItem("DICT", userData="""def parse(line):
    try:
        line = line.split("#")[1]
        k = line.split(":")
        return  {k[0].strip(): k[1].strip()}
    except:
        return {}
""")
        self.parserComboBox.addItem("DICT+CODE", userData="""def parse(line):
    try:
        line = line.split("#")[1]
        k = line.split(":")
        return  {
            k[0].strip(): " ".join(k[1].strip().split(" ")[1:]),
            k[0].strip() + "_CODE": k[1].strip().split(" ")[0]
        }
    except:
        return {}
""")
        self.parserComboBox.addItem("TOKENS", userData="""def generic_parse_with_tokens(input_string):
    import re
    separator=":"
    
    try:
        pattern_parts = []
    
        for token in tokens:
            pattern_parts.append(rf"{token}\s*{separator}\s*(?P<{token}>.+?)\s+")
        pattern = ''.join(pattern_parts).strip()
        match = re.search(pattern, input_string)
        parsed_dict = {}
        if match:
            parsed_dict = {key: match.group(key).strip() for key in match.groupdict()}

        return parsed_dict

    except Exception as e:
        print(f"An error occurred: {e}")
        return {}
""")
        self.clusterConfigsFormLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.parserComboBox)


        self.clusteringFormLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.clusterConfigsFormLayout)
        self.clusteringDetailsHorizontalLayout.addLayout(self.clusteringFormLayout)
        self.clusteringVerticalLayout.addLayout(self.clusteringDetailsHorizontalLayout)
        self.tabWidget.addTab(self.tabClustering, "")
        self.tabExport = QtWidgets.QWidget()
        self.tabExport.setObjectName("tabExport")

        self.clusteringVerticalLayout2 = QtWidgets.QVBoxLayout(self.tabExport)
        self.clusteringVerticalLayout2.setObjectName("clusteringVerticalLayout2")
        self.clusteringHorizontalLayout2 = QtWidgets.QHBoxLayout()
        self.clusteringHorizontalLayout2.setObjectName("clusteringHorizontalLayout2")


        self.exportClusterButton = QtWidgets.QPushButton(self.tabClustering)
        self.exportClusterButton.setObjectName("exportClusterButton")
        self.clusteringHorizontalLayout2.addWidget(self.exportClusterButton)

        self.generateClusterButton = QtWidgets.QPushButton(self.tabClustering)
        self.generateClusterButton.setObjectName("generateClusterButton")
        self.clusteringHorizontalLayout2.addWidget(self.generateClusterButton)
        self.runTaggerButton = QtWidgets.QPushButton(self.tabClustering)
        self.runTaggerButton.setObjectName("runTaggerButton")
        self.clusteringHorizontalLayout2.addWidget(self.runTaggerButton)
        self.runParserButton = QtWidgets.QPushButton(self.tabClustering)
        self.runParserButton.setObjectName("runParserButton")
        self.clusteringHorizontalLayout2.addWidget(self.runParserButton)

        self.runParserButton2 = QtWidgets.QPushButton(self.tabClustering)
        self.runParserButton2.setObjectName("runParserButton2")
        self.clusteringHorizontalLayout2.addWidget(self.runParserButton2)

        self.techniquesComboBox = QtWidgets.QComboBox(self.tabPreprocessing)
        self.techniquesComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.techniquesComboBox.setObjectName("techniquesComboBox")
        self.techniquesComboBox.addItem("Up2Down")
        self.techniquesComboBox.addItem("Down2Up")
        self.clusteringHorizontalLayout2.addWidget(self.techniquesComboBox)


        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.clusteringHorizontalLayout2.addItem(spacerItem2)

        self.clusteringVerticalLayout2.addLayout(self.clusteringHorizontalLayout2)
        self.tabExport.setLayout(self.clusteringVerticalLayout2)


        self.tabWidget.addTab(self.tabExport, "")
        self.mainVerticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1070, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNewProject = QtWidgets.QAction(MainWindow)
        self.actionNewProject.setObjectName("actionNewProject")
        self.actionOpenProject = QtWidgets.QAction(MainWindow)
        self.actionOpenProject.setObjectName("actionOpenProject")
        self.actionSaveProject = QtWidgets.QAction(MainWindow)
        self.actionSaveProject.setObjectName("actionSaveProject")
        self.menuFile.addAction(self.actionNewProject)
        self.menuFile.addAction(self.actionOpenProject)
        self.menuFile.addAction(self.actionSaveProject)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBoxMainText.setTitle(_translate("MainWindow", "Main Text"))
        self.openMainTextButton.setText(_translate("MainWindow", "Open"))
        self.reloadMainTextButton.setText(_translate("MainWindow", "Reload"))
        self.groupBoxAlternativeText.setTitle(_translate("MainWindow", "Alternative Text"))
        self.openAlternativeTextButton.setText(_translate("MainWindow", "Open"))
        self.reloadAlternativeTextButton.setText(_translate("MainWindow", "Reload"))
        self.clearPreprocessingButton.setText(_translate("MainWindow", "Clear"))
        self.applyPreprocessingButton.setText(_translate("MainWindow", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPreprocessing), _translate("MainWindow", "Preprocessing"))
        self.clearTranslationsButton.setText(_translate("MainWindow", "Clear"))
        self.applyTranslationsButton.setText(_translate("MainWindow", "Apply"))
        self.addTranslationButton.setText(_translate("MainWindow", "Add"))
        self.editTranslationButton.setText(_translate("MainWindow", "Edit"))
        self.deleteTranslationButton.setText(_translate("MainWindow", "Delete"))
        item = self.translationsTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Original"))
        item = self.translationsTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Replacement"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTranslations), _translate("MainWindow", "Translations"))

        self.clearMappingsButton.setText(_translate("MainWindow", "Clear"))
        self.applyMappingsButton.setText(_translate("MainWindow", "Apply"))
        self.addMappingButton.setText(_translate("MainWindow", "Add"))
        self.editMappingButton.setText(_translate("MainWindow", "Edit"))
        self.deleteMappingButton.setText(_translate("MainWindow", "Delete"))
        item = self.mappingsTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Original"))
        item = self.mappingsTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Replacement"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMappings),
                                  _translate("MainWindow", "Mappings"))

        self.clearClusteringButton.setText(_translate("MainWindow", "Clear"))
        self.applyClusteringButton.setText(_translate("MainWindow", "Apply"))
        self.addClusterButton.setText(_translate("MainWindow", "Add"))
        self.editClusterButton.setText(_translate("MainWindow", "Edit"))
        self.deleteClusterButton.setText(_translate("MainWindow", "Delete"))
        self.generateClusterButton.setText(_translate("MainWindow", "Generate"))
        self.exportClusterButton.setText(_translate("MainWindow", "Export"))

        self.runTaggerButton.setText(_translate("MainWindow", "Run Tagger"))
        self.runParserButton.setText(_translate("MainWindow", "Run Parser"))
        self.runParserButton2.setText(_translate("MainWindow", "Run Merger"))

        self.labelClusterName.setText(_translate("MainWindow", "Name"))
        self.labelClusterParts.setText(_translate("MainWindow", "Parts"))
        self.labelClusterPatterns.setText(_translate("MainWindow", "Patterns"))
        self.labelClusterCode.setText(_translate("MainWindow", "Code"))
        self.addPartButton.setText(_translate("MainWindow", "Add"))
        self.editPartButton.setText(_translate("MainWindow", "Edit"))
        self.deletePartButton.setText(_translate("MainWindow", "Delete"))
        self.addPatternButton.setText(_translate("MainWindow", "Add"))
        self.editPatternButton.setText(_translate("MainWindow", "Edit"))
        self.deletePatternButton.setText(_translate("MainWindow", "Delete"))
        self.labelClusterConfigs.setText(_translate("MainWindow", "configs"))
        self.labelMinLength.setText(_translate("MainWindow", "Min Length"))
        self.lineEditMinLength.setText(_translate("MainWindow", "200"))
        self.labelMaxLength.setText(_translate("MainWindow", "Max Length"))
        self.lineEditMaxLength.setText(_translate("MainWindow", "100"))
        self.labelPartsWeight.setText(_translate("MainWindow", "Parts weight"))
        self.labelRegexWeight.setText(_translate("MainWindow", "Regex weight"))
        self.lineEditPartsWeight.setText(_translate("MainWindow", "1"))
        self.lineEditRegexWeight.setText(_translate("MainWindow", "1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabClustering), _translate("MainWindow", "Clustering"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabExport), _translate("MainWindow", "Export"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionNewProject.setText(_translate("MainWindow", "New Project"))
        self.actionOpenProject.setText(_translate("MainWindow", "Open Project"))
        self.actionSaveProject.setText(_translate("MainWindow", "Save Project"))



